public enum MessageType {

	REGISTER, LOGIN, USER, ITEM, AUTHENTICATED, FAILED, USERSUCCESS, USERFAIL, UPDATEITEMS, ITEMFAIL, UPDATEBIDS,
	NEWBID, ITEMEND, NOTIFYBID, NOTIFYWIN, NOTIFYFAIL, PENALTY, ITEMCLOSE, SHUTDOWNCLIENT, CLOSESERVER
}
